spring:

  flyway:
    enabled: false

  jpa:
    show-sql: false

  h2:
    console:
      enabled: false

csr:
  regions:
    - name: 1
      url: ${csr.region1.url}
      username: ${csr.region1.username}
      password: ${csr.region1.password}
      driverClassName: oracle.jdbc.OracleDriver
    - name: 2
      url: ${csr.region2.url}
      username: ${csr.region2.username}
      password: ${csr.region2.password}
      driverClassName: oracle.jdbc.OracleDriver
    - name: 3
      url: ${csr.region3.url}
      username: ${csr.region3.username}
      password: ${csr.region3.password}
      driverClassName: oracle.jdbc.OracleDriver
    - name: 4
      url: ${csr.region4.url}
      username: ${csr.region4.username}
      password: ${csr.region4.password}
      driverClassName: oracle.jdbc.OracleDriver
    - name: 5
      url: ${csr.region5.url}
      username: ${csr.region5.username}
      password: ${csr.region5.password}
      driverClassName: oracle.jdbc.OracleDriver
    - name: 6
      url: ${csr.region6.url}
      username: ${csr.region6.username}
      password: ${csr.region6.password}
      driverClassName: oracle.jdbc.OracleDriver