spring:

  flyway:
    enabled: false

  jpa:
    show-sql: false

  h2:
    console:
      enabled: false

  datasource:
    hikari:
      read-only: true

csr:
  regions:
    - name: 1
      url: jdbc:oracle:thin:@localhost:1521/iwfmt3_standby
      username: iwfm_anon
      password: iwfm_anon
      driverClassName: oracle.jdbc.OracleDriver
    - name: 2
      url: jdbc:oracle:thin:@localhost:1521/iwfmt3_standby
      username: iwfm_anon
      password: iwfm_anon
      driverClassName: oracle.jdbc.OracleDriver
    - name: 3
      url: jdbc:oracle:thin:@localhost:1521/iwfmt3_standby
      username: iwfm_anon
      password: iwfm_anon
      driverClassName: oracle.jdbc.OracleDriver
    - name: 4
      url: jdbc:oracle:thin:@localhost:1521/iwfmt3_standby
      username: iwfm_anon
      password: iwfm_anon
      driverClassName: oracle.jdbc.OracleDriver
    - name: 5
      url: jdbc:oracle:thin:@localhost:1521/iwfmt3_standby
      username: iwfm_anon
      password: iwfm_anon
      driverClassName: oracle.jdbc.OracleDriver
    - name: 6
      url: jdbc:oracle:thin:@localhost:1521/iwfmt3_standby
      username: iwfm_anon
      password: iwfm_anon
      driverClassName: oracle.jdbc.OracleDriver