spring:

  flyway:
    enabled: false

  jpa:
    show-sql: false

  h2:
    console:
      enabled: false

  datasource:
    hikari:
      read-only: true

csr:
  url: ${csr.database.url}
  username: ${csr.database.username}
  password: ${csr.database.password}
  driverClassName: oracle.jdbc.OracleDriver
  regions:
    - name: 1
      schema: ${csr.region1.schema}
    - name: 2
      schema: ${csr.region2.schema}
    - name: 3
      schema: ${csr.region3.schema}
    - name: 4
      schema: ${csr.region4.schema}
    - name: 5
      schema: ${csr.region5.schema}
    - name: 6
      schema: ${csr.region6.schema}
