version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.11

executors:
  validator:
    docker:
      - image: cimg/openjdk:16.0-browsers
    working_directory: ~/app

jobs:
  validate:
    executor: validator
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle.kts

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          filters:
            branches:
              only:
                - main
          context:
            - hmpps-common-vars
          requires:
            - validate
            - helm_lint
            - build_docker
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context:
            - csr-api-preprod
            - hmpps-common-vars
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          context:
            - csr-api-prod
            - hmpps-common-vars
          requires:
            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: "34 3 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          context:
            - hmpps-common-vars
            - veracode-credentials
  security-weekly:
    triggers:
      - schedule:
          cron: "12 6 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          context:
            - veracode-credentials
            - hmpps-common-vars
