apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: csr-api
  name: csr-api
spec:
  maxReplicas: {{ .Values.maxReplicaCount }}
  minReplicas: {{ .Values.replicaCount }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: csr-api
  targetCPUUtilizationPercentage: 80
