apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.secrets.APPINSIGHTS_INSTRUMENTATIONKEY | b64enc | quote }}
  CSR_REGION1_URL: {{ .Values.secrets.CSR_REGION1_URL | b64enc | quote }}
  CSR_REGION1_USERNAME: {{ .Values.secrets.CSR_REGION1_USERNAME | b64enc | quote }}
  CSR_REGION1_PASSWORD: {{ .Values.secrets.CSR_REGION1_PASSWORD | b64enc | quote }}
  CSR_REGION2_URL: {{ .Values.secrets.CSR_REGION2_URL | b64enc | quote }}
  CSR_REGION2_USERNAME: {{ .Values.secrets.CSR_REGION2_USERNAME | b64enc | quote }}
  CSR_REGION2_PASSWORD: {{ .Values.secrets.CSR_REGION2_PASSWORD | b64enc | quote }}
  CSR_REGION3_URL: {{ .Values.secrets.CSR_REGION3_URL | b64enc | quote }}
  CSR_REGION3_USERNAME: {{ .Values.secrets.CSR_REGION3_USERNAME | b64enc | quote }}
  CSR_REGION3_PASSWORD: {{ .Values.secrets.CSR_REGION3_PASSWORD | b64enc | quote }}
  CSR_REGION4_URL: {{ .Values.secrets.CSR_REGION4_URL | b64enc | quote }}
  CSR_REGION4_USERNAME: {{ .Values.secrets.CSR_REGION4_USERNAME | b64enc | quote }}
  CSR_REGION4_PASSWORD: {{ .Values.secrets.CSR_REGION4_PASSWORD | b64enc | quote }}
  CSR_REGION5_URL: {{ .Values.secrets.CSR_REGION5_URL | b64enc | quote }}
  CSR_REGION5_USERNAME: {{ .Values.secrets.CSR_REGION5_USERNAME | b64enc | quote }}
  CSR_REGION5_PASSWORD: {{ .Values.secrets.CSR_REGION5_PASSWORD | b64enc | quote }}
  CSR_REGION6_URL: {{ .Values.secrets.CSR_REGION6_URL | b64enc | quote }}
  CSR_REGION6_USERNAME: {{ .Values.secrets.CSR_REGION6_USERNAME | b64enc | quote }}
  CSR_REGION6_PASSWORD: {{ .Values.secrets.CSR_REGION6_PASSWORD | b64enc | quote }}
