---
generic-service:
  replicaCount: 2

  ingress:
    host: csr-api-preprod.prison.service.justice.gov.uk
    className: modsec-non-prod

  poddisruptionbudget:
    enabled: true
    minAvailable: 1

  scheduledDowntime:
    enabled: true
    startup: '15 6 * * 1-5' # Start at 6.15am UTC Monday-Friday
    shutdown: '55 21 * * 1-5' # Stop at 9.55pm UTC Monday-Friday

  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod
