# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
maxReplicaCount: 2

image:
  repository: quay.io/hmpps/csr-api
  tag: latest
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: csr-api-prprod.aks-live-1.studio-hosting.service.justice.gov.uk
      cert_secret: csr-api-prprod-tls-secret
  path: /

env:
  JAVA_OPTS: "-Xmx1536m"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
  OAUTH_ROOT_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
